### ISSUE TITLE
OnType can kill itself

### ISSUE THREAD

**Issue by Madpeterz** [wongjn/vscode-php-sniffer#43]
**Describe the bug**
OnType phpcs updates fail to start.

**To Reproduce**
1. use vs code for a while
2. notice it stopped running phpcs
3. save to see the fixed issues
4. restart vscode to restore ontype

**Expected behavior**
ontype to not kill itself, and if it does
to wait and auto recover.
Only if it was working before and the phpcs.xml config
has not changed.

**Environment**
 - OS: windows 10
 - VSCode version: 1.50.1 (User setup)
 - PHP CLI version: 7.4.11 @ built: sep 29 2020 [Zend v3.4.0]
 - squizlabs/PHP_CodeSniffer version: Global

**Extension settings**
```json
{
    "phpSniffer.run": "onType",
    "phpSniffer.onTypeDelay": 120,
    "phpSniffer.autoDetect": true,
}
```

**Comment by wongjn** [comment]
Thank you for your bug report. To help debug the issue, when you notice it happening again, please open devtools and copy-paste any relevant output you see in the console.

**Comment by Madpeterz** [comment]
Heres what I noticed not sure if its from your code thou.

`
potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ event.ts:420

    at file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:94:458
    at Object.onFirstListenerAdd (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:94:598)
    at _event._event (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:97:930)
    at new g (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4979:596)
    at d._createInstance (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1690:671)
    at d.createInstance (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1690:92)
    at p.showViewActivity (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4980:725)
    at f.renderActivityCount (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6048:814)
    at file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6047:161
    at file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:219
    at c.fire (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:801)
    at e.$spliceGroupResourceStates (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4559:606)
    at m.$spliceResourceStates (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4561:663)
    at p._doInvokeHandler (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4599:202)
    at p._invokeHandler (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4598:901)
    at p._receiveRequest (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4597:510)
    at p._receiveOneMessage (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4596:283)
    at file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4594:400
    at c.fire (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:801)
    at fire (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:454:878)
    at t.PersistentProtocol._receiveMessage (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:459:921)
    at file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:456:984
    at c.fire (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:801)
    at g.acceptChunk (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:452:306)
    at file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:451:657
    at Socket.t (file:///D:/Users/Madpeter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:461:515)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
`

**Comment by wongjn** [comment]
Thank you for the information. So if we try to investigate per the output you gave, what is your typical workflow? Do you open & close lots of files in one VSCode session? Or anything that might help to reproduce the issue?

**Comment by Madpeterz** [comment]
I had been moving folders around as well as coding and renaming files.
but not at the time it stopped.

**Comment by Madpeterz** [comment]
VScode has updated and im not able to repeat this issue 

vscode: 1.51.1
sniffer: v1.2.6

closing for now
